# Generated by Django 6.0.4 on 2026-04-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('jumlah_anggota', models.IntegerField()),
                ('jumlah_tanggungan', models.IntegerField()),
                ('pendapatan', models.CharField(max_length=50)),
                ('pekerjaan', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
