# Generated by Codex on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warga',
            name='firebase_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='warga',
            name='foto_aset',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='warga',
            name='foto_rumah',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='warga',
            name='kepemilikan_aset',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='warga',
            name='kepemilikan_usaha',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='warga',
            name='nilai_akhir',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='warga',
            name='riwayat_bantuan',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='warga',
            name='status_approval',
            field=models.CharField(blank=True, default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='warga',
            name='status_kk',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='warga',
            name='status_pekerjaan',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='warga',
            name='status_tinggal',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='warga',
            name='sumber_air',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='warga',
            name='tanggal',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='warga',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
